# Generated by Django 3.0 on 2020-03-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.IntegerField(max_length=5, verbose_name='菜单ID')),
                ('title', models.CharField(max_length=10, verbose_name='菜单标题')),
            ],
        ),
    ]
