# Generated by Django 3.0 on 2020-03-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='menu_id',
            field=models.IntegerField(verbose_name='菜单ID'),
        ),
    ]
