# Generated by Django 3.0 on 2020-03-19 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0002_auto_20200319_0029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menus',
            options={'verbose_name': '菜单项', 'verbose_name_plural': '菜单项'},
        ),
        migrations.AddField(
            model_name='menus',
            name='level',
            field=models.CharField(choices=[(1, '一级菜单'), (2, '二级菜单')], default=1, max_length=5, verbose_name='菜单级别'),
        ),
        migrations.AddField(
            model_name='menus',
            name='parent',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='restfulapi.Menus', verbose_name='父节点'),
        ),
    ]
