# Generated by Django 3.0 on 2020-03-19 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi', '0003_auto_20200319_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='level',
            field=models.IntegerField(choices=[(1, '一级菜单'), (2, '二级菜单')], default=1, verbose_name='菜单级别'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to='restfulapi.Menus', verbose_name='父节点'),
        ),
    ]
