# Generated by Django 3.0 on 2020-03-20 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('restfulapi', '0006_menus_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, related_name='group_menus', to='auth.Group', verbose_name='分组'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='parent',
            field=models.ForeignKey(blank=True, max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subMenu', to='restfulapi.Menus', verbose_name='父节点'),
        ),
        migrations.AlterField(
            model_name='menus',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='url'),
        ),
    ]
