# Generated by Django 3.0 on 2020-03-20 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('restfulapi', '0007_auto_20200320_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menus',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='group_menus', to='auth.Group', verbose_name='分组'),
        ),
    ]
