# Generated by Django 3.0 on 2020-01-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='姓名'),
            preserve_default=False,
        ),
    ]
