# Generated by Django 3.0 on 2020-03-17 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_token_userinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
