# Generated by Django 3.0 on 2019-12-10 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10, verbose_name='设备编号')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('model', models.CharField(max_length=50, verbose_name='规格型号')),
                ('detection_department', models.CharField(max_length=50, verbose_name='检定机构')),
                ('detection_period', models.IntegerField(verbose_name='检定周期（月）')),
                ('last_detection', models.DateField(verbose_name='上次检定时间')),
                ('next_detection', models.DateField(verbose_name='下次检定时间')),
            ],
            options={
                'verbose_name': '设备',
                'verbose_name_plural': '设备',
                'ordering': ('device_id',),
            },
        ),
    ]
