# Generated by Django 3.0 on 2019-12-10 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('legal_personality', models.CharField(max_length=50, verbose_name='法人')),
                ('range_approved', models.TextField(verbose_name='经营范围')),
                ('supervision', models.CharField(max_length=100, verbose_name='业务主管部门')),
                ('license_num', models.CharField(max_length=50, verbose_name='执业许可证号')),
                ('bank', models.CharField(max_length=50, verbose_name='开户行名称')),
                ('account', models.IntegerField(verbose_name='开户行账号')),
                ('org_id', models.CharField(max_length=50, verbose_name='统一社会信用代码')),
                ('contact', models.CharField(max_length=50, verbose_name='联系人')),
                ('phone_1', models.CharField(max_length=20, verbose_name='联系电话1')),
                ('phone_2', models.CharField(max_length=20, verbose_name='联系电话2')),
                ('fax', models.CharField(max_length=20, verbose_name='传真')),
                ('complaints_hotline', models.CharField(max_length=20, verbose_name='监督电话')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '机构',
                'verbose_name_plural': '机构',
                'ordering': ('id',),
            },
        ),
    ]
