# Generated by Django 3.0 on 2019-12-10 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0003_auto_20191210_0333'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('0', '在库'), ('1', '出库'), ('2', '借出'), ('3', '故障'), ('4', '检定'), ('5', '保养')], default=0, max_length=5, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='WarehouseManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_date', models.DateTimeField(auto_created=True, verbose_name='归还时间')),
                ('apply_date', models.DateTimeField(auto_created=True, verbose_name='申请时间')),
                ('apply_purpose', models.CharField(choices=[('1', '出库'), ('2', '借出'), ('3', '故障'), ('4', '检定'), ('5', '保养')], default=1, max_length=5, verbose_name='申领原因')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '损坏')], default=0, max_length=5, verbose_name='归还状态')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.Devices', verbose_name='设备')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='申领人')),
            ],
        ),
    ]
