# Generated by Django 3.0 on 2019-12-11 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0004_auto_20191210_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_date', models.DateTimeField(auto_created=True, verbose_name='申请时间')),
                ('apply_purpose', models.CharField(choices=[('1', '项目申领'), ('2', '借出'), ('3', '维修'), ('4', '检定'), ('5', '保养')], default=1, max_length=5, verbose_name='申领原因')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('status', models.CharField(default=0, max_length=5, verbose_name='状态')),
                ('devices_apply', models.ManyToManyField(related_name='apply_records', to='appraisal.Devices', verbose_name='申领设备')),
                ('devices_return', models.ManyToManyField(related_name='return_records', to='appraisal.Devices', verbose_name='设备归还')),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='申领人')),
            ],
        ),
        migrations.DeleteModel(
            name='WarehouseManagement',
        ),
    ]
