# Generated by Django 3.0 on 2019-12-11 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0005_auto_20191211_0141'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyrecord',
            options={'ordering': ('-apply_date', 'status'), 'verbose_name': '仪器申领', 'verbose_name_plural': '仪器申领'},
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='devices_return',
            field=models.ManyToManyField(related_name='return_records', to='appraisal.Devices', verbose_name='归还设备'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='status',
            field=models.CharField(choices=[('0', '未完成'), ('1', '完成')], default=0, max_length=5, verbose_name='状态'),
        ),
    ]
