# Generated by Django 3.0 on 2019-12-11 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0010_auto_20191211_0345'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterModelOptions(
            name='applyrecord',
            options={'verbose_name': '仪器申领', 'verbose_name_plural': '仪器申领'},
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='apply_date',
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='devices_apply',
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='devices_return',
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='return_date',
        ),
        migrations.CreateModel(
            name='ApplyDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apply_time', models.DateTimeField(auto_created=True, verbose_name='申领时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.Devices', verbose_name='申领设备')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.ApplyRecord', verbose_name='申领表')),
            ],
        ),
    ]
