# Generated by Django 3.0 on 2019-12-11 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0011_auto_20191211_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applydevice',
            options={'verbose_name': '申领设备', 'verbose_name_plural': '申领设备'},
        ),
    ]
