# Generated by Django 3.0 on 2019-12-11 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0012_auto_20191211_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20, verbose_name='状态')),
            ],
        ),
        migrations.AlterModelOptions(
            name='applydevice',
            options={'verbose_name': '设备', 'verbose_name_plural': '设备'},
        ),
        migrations.AlterField(
            model_name='applydevice',
            name='device',
            field=models.ForeignKey(limit_choices_to={'status': 0}, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.Devices', verbose_name='申领设备'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='apply_purpose',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.DeviceStatus', verbose_name='申领原因'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.DeviceStatus', verbose_name='设备状态'),
        ),
    ]
