# Generated by Django 3.0 on 2019-12-11 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0013_auto_20191211_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applyrecord',
            name='apply_purpose',
        ),
        migrations.RemoveField(
            model_name='devices',
            name='status',
        ),
    ]
