# Generated by Django 3.0 on 2019-12-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0017_auto_20191211_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devices',
            name='status',
        ),
    ]
