# Generated by Django 3.0 on 2019-12-11 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0018_remove_devices_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.DeviceStatus', verbose_name='设备状态'),
        ),
    ]
