# Generated by Django 3.0 on 2019-12-11 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0021_auto_20191211_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.DeviceStatus', verbose_name='设备状态'),
        ),
    ]
