# Generated by Django 3.0 on 2019-12-11 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0022_auto_20191211_1909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyrecord',
            options={'verbose_name': '设备仪器申领', 'verbose_name_plural': '设备仪器申领'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ('device_id',), 'verbose_name': '设备仪器', 'verbose_name_plural': '设备仪器'},
        ),
        migrations.AlterModelOptions(
            name='devicestatus',
            options={'ordering': ('id',), 'verbose_name': '设备仪器状态', 'verbose_name_plural': '设备仪器状态'},
        ),
        migrations.AlterField(
            model_name='applydevice',
            name='device',
            field=models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.Devices', verbose_name='申领设备'),
        ),
    ]
