# Generated by Django 3.0 on 2019-12-11 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0023_auto_20191211_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applydevice',
            name='device',
            field=models.ForeignKey(limit_choices_to={'status__status': '在库'}, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.Devices', verbose_name='申领设备'),
        ),
    ]
