# Generated by Django 3.0 on 2019-12-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0024_auto_20191211_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrecord',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='备注'),
        ),
    ]
