# Generated by Django 3.0 on 2019-12-11 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0026_auto_20191211_2128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseInfo',
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='apply_purpose',
        ),
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.CharField(choices=[('1', '在库'), ('2', '出库')], default=1, max_length=5, verbose_name='库存状态'),
        ),
    ]
