# Generated by Django 3.0 on 2019-12-12 00:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0027_auto_20191211_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applydevice',
            name='apply_time',
        ),
        migrations.RemoveField(
            model_name='applydevice',
            name='is_return',
        ),
        migrations.RemoveField(
            model_name='applydevice',
            name='return_time',
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='created_time',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2019, 12, 12, 0, 18, 37, 304400), verbose_name='申领时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='is_return',
            field=models.BooleanField(default=False, verbose_name='是否归还'),
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='return_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='归还时间'),
        ),
        migrations.AlterField(
            model_name='applydevice',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.Devices', verbose_name='申领设备'),
        ),
    ]
