# Generated by Django 3.0 on 2019-12-12 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0028_auto_20191212_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='申领时间'),
        ),
    ]
