# Generated by Django 3.0 on 2019-12-12 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0029_auto_20191212_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='申领时间'),
        ),
    ]
