# Generated by Django 3.0 on 2019-12-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0030_auto_20191212_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='鉴定用途')),
            ],
            options={
                'verbose_name': '鉴定用途',
                'verbose_name_plural': '鉴定用途',
            },
        ),
        migrations.CreateModel(
            name='AppraisalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='鉴定类别')),
            ],
            options={
                'verbose_name': '鉴定类别',
                'verbose_name_plural': '鉴定类别',
            },
        ),
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('principal', models.CharField(max_length=50, verbose_name='委托人')),
                ('detail', models.TextField(verbose_name='委托事项')),
                ('re_appraisal', models.BooleanField(verbose_name='是否重新鉴定')),
                ('target', models.CharField(max_length=50, verbose_name='被鉴定对象')),
                ('org', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.Organization', verbose_name='鉴定机构')),
                ('purpose', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.AppraisalPurpose', verbose_name='鉴定用途')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.AppraisalType', verbose_name='鉴定类别')),
            ],
            options={
                'verbose_name': '鉴定项目基础信息',
                'verbose_name_plural': '鉴定项目基础信息',
            },
        ),
    ]
