# Generated by Django 3.0 on 2019-12-17 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0031_appraisalpurpose_appraisaltype_basicinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
    ]
