# Generated by Django 3.0 on 2019-12-17 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0032_auto_20191217_1815'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicinfo',
            old_name='re_appraisal',
            new_name='is_re_appraisal',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='appraisal_team',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='鉴定人'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='受理时间'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='finished_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成时间'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='鉴定编号'),
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='target_address',
            field=models.CharField(default='', max_length=100, verbose_name='鉴定地址'),
            preserve_default=False,
        ),
    ]
