# Generated by Django 3.0 on 2019-12-18 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0033_auto_20191217_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='reviewer',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_reviewer': True}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='appraisal_team',
            field=models.ManyToManyField(related_name='appraisal_team', to=settings.AUTH_USER_MODEL, verbose_name='鉴定人'),
        ),
    ]
