# Generated by Django 3.0 on 2019-12-18 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0034_auto_20191218_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='材料名称')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('received_date', models.DateField(verbose_name='接收时间')),
            ],
            options={
                'verbose_name': '鉴定材料',
                'verbose_name_plural': '鉴定材料',
            },
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.CreateModel(
            name='SampleRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('is_returned', models.BooleanField(verbose_name='是否归还')),
                ('comment', models.TextField(verbose_name='备注')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='借阅人')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.Sample', verbose_name='材料')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='basic_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.BasicInfo', verbose_name='基础信息'),
        ),
        migrations.AddField(
            model_name='sample',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
    ]
