# Generated by Django 3.0 on 2019-12-25 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0035_auto_20191218_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished_date', models.DateField(blank=True, null=True, verbose_name='完成时间')),
                ('file_date', models.DateField(blank=True, null=True, verbose_name='归档日期')),
                ('delivery', models.CharField(choices=[(0, '未送达'), (1, '邮寄'), (2, '专人送达'), (3, '自取')], default=0, max_length=2, verbose_name='送达方式')),
                ('amount', models.IntegerField(verbose_name='份数')),
            ],
        ),
        migrations.AlterModelOptions(
            name='samplerecord',
            options={'verbose_name': '借料借阅记录', 'verbose_name_plural': '借料借阅记录'},
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='appraisal_team',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='detail',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='finished_date',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='reviewer',
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='target_address',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='trust_detail',
            field=models.TextField(blank=True, null=True, verbose_name='委托事项'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.AppraisalPurpose', verbose_name='案由/鉴定用途'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sn',
            field=models.CharField(default='', max_length=50, verbose_name='鉴定编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sample',
            name='basic_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.BasicInfo', verbose_name='基本信息'),
        ),
        migrations.CreateModel(
            name='AppraisalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(blank=True, null=True, verbose_name='受理时间')),
                ('opinion', models.TextField(blank=True, null=True, verbose_name='主要鉴定意见')),
                ('appraisal_address', models.CharField(max_length=50, verbose_name='鉴定地址')),
                ('project_detail', models.TextField(blank=True, null=True, verbose_name='基本案情')),
                ('contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('trust_date', models.DateField(blank=True, null=True, verbose_name='委托时间')),
                ('appraisal_date', models.DateField(verbose_name='鉴定时间')),
                ('discuss_date', models.DateField(blank=True, null=True, verbose_name='讨论时间')),
                ('appraisal_team', models.ManyToManyField(related_name='appraisal_team', to=settings.AUTH_USER_MODEL, verbose_name='鉴定人')),
                ('archivist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archivist', to=settings.AUTH_USER_MODEL, verbose_name='立卷人')),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.BasicInfo', verbose_name='基础信息')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='复核人')),
            ],
        ),
        migrations.AddField(
            model_name='sample',
            name='appraisal_info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='appraisal.AppraisalInfo', verbose_name='鉴定信息'),
            preserve_default=False,
        ),
    ]
