# Generated by Django 3.0 on 2020-01-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0038_remove_sample_appraisal_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filephase',
            name='delivery',
            field=models.IntegerField(choices=[(0, '未送达'), (1, '邮寄'), (2, '专人送达'), (3, '自取')], default=0, verbose_name='送达方式'),
        ),
    ]
