# Generated by Django 3.0 on 2020-01-07 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0039_auto_20200102_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ('device_id',), 'verbose_name': '仪器设备库', 'verbose_name_plural': '仪器设备库'},
        ),
    ]
