# Generated by Django 3.0 on 2020-01-07 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0040_auto_20200107_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalinfo',
            name='appraisal_date',
            field=models.DateField(null=True, verbose_name='鉴定时间'),
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='appraisal_team',
            field=models.ManyToManyField(null=True, related_name='appraisal_team', to=settings.AUTH_USER_MODEL, verbose_name='鉴定人'),
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='archivist',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='archivist', to=settings.AUTH_USER_MODEL, verbose_name='立卷人'),
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
    ]
