# Generated by Django 3.0 on 2020-01-07 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0041_auto_20200107_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalinfo',
            name='appraisal_team',
            field=models.ManyToManyField(related_name='appraisal_team', to=settings.AUTH_USER_MODEL, verbose_name='鉴定人'),
        ),
        migrations.AlterField(
            model_name='filephase',
            name='amount',
            field=models.IntegerField(null=True, verbose_name='份数'),
        ),
        migrations.AlterField(
            model_name='filephase',
            name='delivery',
            field=models.IntegerField(choices=[(0, '未送达'), (1, '邮寄'), (2, '专人送达'), (3, '自取')], default=0, null=True, verbose_name='送达方式'),
        ),
    ]
