# Generated by Django 3.0 on 2020-01-09 17:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0043_auto_20200107_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalFileRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='借出时间')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('is_returned', models.BooleanField(verbose_name='是否归还')),
                ('comment', models.TextField(verbose_name='备注')),
            ],
            options={
                'verbose_name': '材料借阅记录',
                'verbose_name_plural': '材料借阅记录',
            },
        ),
        migrations.RenameModel(
            old_name='Sample',
            new_name='AppraisalFile',
        ),
        migrations.DeleteModel(
            name='SampleRecord',
        ),
        migrations.AddField(
            model_name='appraisalfilerecord',
            name='appraisal_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.AppraisalFile', verbose_name='材料'),
        ),
        migrations.AddField(
            model_name='appraisalfilerecord',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='借阅人'),
        ),
    ]
