# Generated by Django 3.0 on 2020-01-11 03:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0044_auto_20200109_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppraisalSample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='材料名称')),
                ('quantity', models.IntegerField(verbose_name='数量')),
                ('received_date', models.DateField(verbose_name='接收时间')),
                ('basic_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.BasicInfo', verbose_name='基本信息')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name': '试验检材',
                'verbose_name_plural': '试验检材',
            },
        ),
    ]
