# Generated by Django 3.0 on 2020-03-20 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0048_auto_20200318_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filephase',
            name='basic_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='appraisal.BasicInfo', verbose_name='基础信息'),
        ),
    ]
