# Generated by Django 3.0 on 2020-03-21 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0050_auto_20200321_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalinfo',
            name='archivist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archivist', to=settings.AUTH_USER_MODEL, verbose_name='立卷人'),
        ),
    ]
