# Generated by Django 3.0 on 2020-03-23 00:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0051_auto_20200321_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalinfo',
            name='appraisal_team',
            field=models.ManyToManyField(related_name='appraisal_info', to=settings.AUTH_USER_MODEL, verbose_name='鉴定人'),
        ),
    ]
