# Generated by Django 3.0 on 2020-03-29 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0054_auto_20200323_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='apprfiles/%Y/%m/%d', verbose_name='上传文件'),
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='basic_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appr_info', to='appraisal.BasicInfo', verbose_name='基础信息'),
        ),
    ]
