# Generated by Django 3.0 on 2020-03-29 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0055_auto_20200329_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalfile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='apprfiles/%Y/%m/%d', verbose_name='上传文件'),
        ),
    ]
