# Generated by Django 3.0 on 2020-03-29 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0056_auto_20200329_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalfile',
            name='file',
        ),
        migrations.CreateModel(
            name='AppraisalFileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('file', models.ImageField(blank=True, null=True, upload_to='apprfiles/%Y/%m/%d', verbose_name='上传文件')),
                ('appraisal_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.AppraisalFile', verbose_name='鉴定材料')),
            ],
            options={
                'verbose_name': '鉴定材料文件',
                'verbose_name_plural': '鉴定材料文件',
            },
        ),
    ]
