# Generated by Django 3.0 on 2020-03-30 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0057_auto_20200329_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraisalfileimage',
            name='name',
        ),
        migrations.AlterField(
            model_name='appraisalfileimage',
            name='appraisal_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appraisal.AppraisalFile', verbose_name='鉴定材料'),
        ),
    ]
