# Generated by Django 3.0 on 2020-03-31 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0058_auto_20200330_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appraisalfilerecord',
            name='appraisal_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='appraisal.AppraisalFile', verbose_name='材料'),
        ),
    ]
