# Generated by Django 3.0 on 2020-04-01 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0060_auto_20200331_2353'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocaleFileImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, null=True, upload_to='localefiles/%Y/%m/%d', verbose_name='上传文件')),
                ('locale_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.LocaleFile', verbose_name='现场文件')),
            ],
            options={
                'verbose_name': '现场纸质文件图片',
                'verbose_name_plural': '现场纸质文件图片',
            },
        ),
    ]
