# Generated by Django 3.0 on 2020-04-01 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0061_localefileimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localefile',
            name='file',
        ),
    ]
