# Generated by Django 3.0 on 2020-04-02 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0063_auto_20200402_0426'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='id_finished',
            field=models.BooleanField(default=False, verbose_name='是否完工'),
        ),
    ]
