# Generated by Django 3.0 on 2020-04-02 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0065_auto_20200402_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='is_finished',
        ),
        migrations.AddField(
            model_name='basicinfo',
            name='stage',
            field=models.IntegerField(default=0, verbose_name='所处阶段'),
        ),
    ]
