# Generated by Django 3.0 on 2020-04-03 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0066_auto_20200402_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='stage',
            field=models.IntegerField(default=1, verbose_name='所处阶段'),
        ),
    ]
