# Generated by Django 3.0 on 2020-04-03 03:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0067_auto_20200403_0202'),
    ]

    operations = [
        migrations.AddField(
            model_name='filephase',
            name='archivist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='归档人'),
        ),
    ]
