# Generated by Django 3.0 on 2020-04-08 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0072_auto_20200408_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='records', to='appraisal.Devices', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='devicestatus',
            name='code',
            field=models.IntegerField(verbose_name='代码'),
        ),
    ]
