# Generated by Django 3.1 on 2020-09-01 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0074_auto_20200408_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='purpose',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.appraisalpurpose', verbose_name='鉴定用途'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='sn',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='鉴定编号'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.devicestatus', verbose_name='库存状态'),
        ),
    ]
