# Generated by Django 3.1 on 2020-09-01 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0075_auto_20200901_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='appraisalinfo',
            name='proofreader',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='proofreader', to=settings.AUTH_USER_MODEL, verbose_name='校对人'),
        ),
    ]
