# Generated by Django 3.1 on 2020-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0076_appraisalinfo_proofreader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='stage',
            field=models.CharField(choices=[('1', '在库'), ('2', '出库')], max_length=1, verbose_name='项目所处阶段'),
        ),
    ]
