# Generated by Django 3.1 on 2020-09-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0079_auto_20200904_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='stage',
            field=models.IntegerField(choices=[('1', '立项中'), ('2', '立项提交'), ('3', '立卷中'), ('4', '立卷提交'), ('5', '校对中'), ('6', '校对提交'), ('7', '审核中'), ('8', '审核提交'), ('9', '归档')], verbose_name='项目所处阶段'),
        ),
    ]
