# Generated by Django 3.1 on 2020-09-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0080_auto_20200904_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='stage',
            field=models.IntegerField(choices=[('1', '立项中'), ('2', '立项提交'), ('3', '立项审批中'), ('4', '立项审批通过'), ('5', '立卷中'), ('6', '立卷提交'), ('7', '校对中'), ('8', '校对提交'), ('9', '审核中'), ('10', '审核提交'), ('11', '归档')], verbose_name='项目所处阶段'),
        ),
    ]
