# Generated by Django 3.1 on 2020-09-05 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0081_auto_20200905_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='reviewer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='立项审批人'),
        ),
    ]
