# Generated by Django 3.1 on 2020-09-05 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0082_basicinfo_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='立项审批人'),
        ),
    ]
