# Generated by Django 3.1 on 2020-09-05 03:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0083_auto_20200905_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfoReviews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion', models.TextField(verbose_name='审批意见')),
                ('created_time', models.DateTimeField(verbose_name='审批时间')),
                ('is_passed', models.BooleanField(verbose_name='是否通过')),
                ('basicInfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.basicinfo', verbose_name='立项信息')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='审批人')),
            ],
            options={
                'verbose_name': '立项审批记录',
                'verbose_name_plural': '立项审批记录',
            },
        ),
    ]
