# Generated by Django 3.1 on 2020-09-05 04:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0084_basicinforeviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinforeviews',
            name='created_time',
        ),
        migrations.AddField(
            model_name='basicinforeviews',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='审批日期'),
            preserve_default=False,
        ),
    ]
