# Generated by Django 3.1 on 2020-09-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0085_auto_20200905_0419'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinforeviews',
            name='status',
            field=models.IntegerField(choices=[(0, '暂存'), (1, '提交'), (2, '打回')], default=1, verbose_name='操作类型'),
            preserve_default=False,
        ),
    ]
