# Generated by Django 3.1 on 2020-09-06 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0086_basicinforeviews_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinforeviews',
            name='is_passed',
        ),
    ]
