# Generated by Django 3.1 on 2020-09-14 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0088_auto_20200914_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkrecord',
            options={'verbose_name': '审批记录', 'verbose_name_plural': '审批记录'},
        ),
    ]
