# Generated by Django 3.1 on 2020-09-21 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0091_todolist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addifileimage',
            options={'verbose_name': '附加材料图片', 'verbose_name_plural': '附加材料图片'},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'verbose_name': '待办事项', 'verbose_name_plural': '待办事项'},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 21, 17, 1, 8, 595878), verbose_name='创建时间'),
        ),
    ]
