# Generated by Django 3.1 on 2020-09-22 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0093_auto_20200921_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='creator', to='account.customuser', verbose_name='立项人'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='final_reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='final_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='立项审批人'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
