# Generated by Django 3.1 on 2020-09-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0094_auto_20200922_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrecord',
            name='status',
            field=models.IntegerField(choices=[('t', '暂存'), ('s', '提交'), ('r', '打回')], verbose_name='操作类型'),
        ),
    ]
