# Generated by Django 3.1 on 2020-09-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0097_todolist_is_back'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkrecord',
            name='status',
            field=models.CharField(choices=[('t', '暂存'), ('s', '提交'), ('b', '打回')], max_length=1, verbose_name='操作类型'),
        ),
    ]
