# Generated by Django 3.1 on 2020-09-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0098_auto_20200924_0842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todolist',
            old_name='is_Back',
            new_name='is_back',
        ),
    ]
