# Generated by Django 3.1 on 2020-09-27 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0099_auto_20200924_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='type',
            field=models.IntegerField(choices=[(1, '立项'), (2, '初审'), (3, '立卷'), (4, '校对'), (5, '终审'), (6, '归档')], verbose_name='事项类型'),
        ),
    ]
