# Generated by Django 3.1 on 2020-09-27 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0100_auto_20200927_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='类别')),
            ],
            options={
                'verbose_name': '设备分类',
                'verbose_name_plural': '设备分类',
            },
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='device',
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='is_returned',
        ),
        migrations.RemoveField(
            model_name='applyrecord',
            name='return_time',
        ),
        migrations.AddField(
            model_name='applyrecord',
            name='basic_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.basicinfo', verbose_name='相关项目'),
        ),
        migrations.CreateModel(
            name='ApplyRecordDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.BooleanField(default=False, verbose_name='是否归还')),
                ('return_time', models.DateTimeField(blank=True, null=True, verbose_name='归还时间')),
                ('apply_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.applyrecord', verbose_name='出库批次')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.devices', verbose_name='设备')),
            ],
            options={
                'verbose_name': '设备仪器出入库明细',
                'verbose_name_plural': '设备仪器出入库明细',
            },
        ),
    ]
