# Generated by Django 3.1 on 2020-09-27 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0102_devices_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.devicegroup', verbose_name='分类'),
        ),
    ]
