# Generated by Django 3.1 on 2020-09-28 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0103_auto_20200927_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='devices', to='appraisal.devicegroup', verbose_name='分类'),
        ),
    ]
