# Generated by Django 3.1 on 2020-09-28 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0104_auto_20200928_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecorddetail',
            name='return_time',
            field=models.DateTimeField(auto_now=True, verbose_name='归还时间'),
        ),
    ]
