# Generated by Django 3.1.3 on 2020-12-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0106_auto_20201208_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyPurpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='申领原因')),
                ('code', models.CharField(max_length=5, verbose_name='编码')),
            ],
            options={
                'verbose_name': '设备申领原因',
                'verbose_name_plural': '设备申领原因',
                'ordering': ('-code',),
            },
        ),
    ]
