# Generated by Django 3.1.3 on 2020-12-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0107_applypurpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyrecord',
            name='apply_purpose',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.applypurpose', verbose_name='申领原因'),
        ),
    ]
