# Generated by Django 3.1.3 on 2021-01-06 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0110_auto_20210106_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecorddetail',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='appraisal.devices', verbose_name='设备'),
        ),
    ]
