# Generated by Django 3.1.3 on 2021-01-06 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appraisal', '0111_auto_20210106_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applyrecord',
            name='apply_purpose',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.applypurpose', verbose_name='申领原因'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='basic_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.basicinfo', verbose_name='相关项目'),
        ),
        migrations.AlterField(
            model_name='applyrecord',
            name='proposer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='申领人'),
        ),
        migrations.AlterField(
            model_name='applyrecorddetail',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appraisal.devices', verbose_name='设备'),
        ),
        migrations.AlterField(
            model_name='appraisalfile',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AlterField(
            model_name='appraisalfilerecord',
            name='borrower',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='借阅人'),
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='archivist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivist', to=settings.AUTH_USER_MODEL, verbose_name='立卷人'),
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='final_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='final_reviewer', to=settings.AUTH_USER_MODEL, verbose_name='复核人'),
        ),
        migrations.AlterField(
            model_name='appraisalinfo',
            name='proofreader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proofreader', to=settings.AUTH_USER_MODEL, verbose_name='校对人'),
        ),
        migrations.AlterField(
            model_name='appraisalsample',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='接收人'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='立项人'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.organization', verbose_name='鉴定机构'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='立项审批人'),
        ),
        migrations.AlterField(
            model_name='checkrecord',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='审批人'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='appraisal.devicegroup', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.devicestatus', verbose_name='库存状态'),
        ),
        migrations.AlterField(
            model_name='filephase',
            name='archivist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='归档人'),
        ),
        migrations.AlterField(
            model_name='filephase',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appraisal.deliverystate', verbose_name='送达状态'),
        ),
    ]
