# Generated by Django 3.1.3 on 2021-01-07 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0112_auto_20210106_2331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addifileimage',
            options={'verbose_name': '附加资料图片', 'verbose_name_plural': '附加资料图片'},
        ),
        migrations.AlterModelOptions(
            name='appraisalfilerecord',
            options={'verbose_name': '鉴定材料借阅记录', 'verbose_name_plural': '鉴定材料借阅记录'},
        ),
        migrations.AlterModelOptions(
            name='appraisalinfo',
            options={'verbose_name': '鉴定信息', 'verbose_name_plural': '鉴定信息'},
        ),
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'verbose_name': '立项信息', 'verbose_name_plural': '立项信息'},
        ),
        migrations.AlterModelOptions(
            name='filephase',
            options={'verbose_name': '归档信息', 'verbose_name_plural': '归档信息'},
        ),
        migrations.AlterField(
            model_name='addifileimage',
            name='addiFile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='appraisal.additionalfile', verbose_name='附加资料'),
        ),
    ]
