# Generated by Django 3.1.3 on 2021-01-08 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0113_auto_20210107_0147'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ('device_id',), 'verbose_name': '设备仪器', 'verbose_name_plural': '设备仪器'},
        ),
    ]
