# Generated by Django 3.1.3 on 2021-01-08 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appraisal', '0114_auto_20210108_0123'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applyrecord',
            options={'verbose_name': '设备仪器申领记录', 'verbose_name_plural': '设备仪器申领记录'},
        ),
    ]
